name: model_safety
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - cudatoolkit=11.3
  - google-api-python-client
  - pip
  - ipython
  - git-lfs
  - pip:
    - pip-tools
    - -r requirements.txt
